# Generated by Django 4.2.7 on 2023-11-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_auto', models.CharField(max_length=200, verbose_name='Марка автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mark', verbose_name='Модель автомобиля')),
            ],
        ),
    ]
