# Generated by Django 4.2.7 on 2023-11-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_auto', models.CharField(max_length=200, verbose_name='Марка автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200, verbose_name='Модель автомобиля')),
                ('model_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='cars.mark')),
            ],
        ),
    ]
